
```{r}
# Current and previous month counts
results_month <- cases_allnephu %>%
  dplyr::filter(condition_label %in% conditions_list) %>%
  #
  f_table_dataprep_count(conditions = conditions_list)

# Monthly means and SDs for four-year lookback period
# High volume conditions
results_mean_high <- cases_allnephu %>% 
  dplyr::filter(condition_label %in% volume_high) %>%
  dplyr::filter(event_yearmonth %in% hlm_baseline) %>%
  #
  f_table_dataprep_mean_highvolume(conditions = volume_high)

# Low volume conditions
results_mean_low <- cases_allnephu %>%
  dplyr::filter(condition_label %in% volume_low) %>%
  #
  f_table_dataprep_mean_lowvolume(conditions = volume_low)
  
# Bind high volume and low volume data
results_mean <- results_mean_high %>% 
  dplyr::bind_rows(results_mean_low) %>%
  #
  dplyr::left_join(
    dplyr::select(reference_conditions, 
                  condition_label, 
                  four_years_data),
    by = "condition_label") %>%
  #
  dplyr::mutate(
    mean_month = dplyr::case_when(four_years_data == "No" ~ NA_integer_,
                                  TRUE ~ mean_month),
    #
    sd_month = dplyr::case_when(four_years_data == "No" ~ NA_integer_,
                                TRUE ~ sd_month),
    #
    limit_sd_upper = mean_month + (sd_month * 2),
    limit_sd_lower = mean_month - (sd_month * 2))

# Join monthly counts and means
results_month <- results_month %>% 
  dplyr::left_join(results_mean, by = "condition_label") %>% 
  #
  dplyr::distinct(condition_label, .keep_all = TRUE) %>% 
  #
  dplyr::mutate(
    sig_month = dplyr::case_when(
      four_years_data == "No" ~ "**",
      #
      n_total_baseline > 0 & n_month_current >= limit_sd_upper ~ "Higher than expected",
      n_total_baseline > 0 & n_month_current <= limit_sd_lower ~ "Lower than expected",
      #
      TRUE ~ "Baseline")) %>% 
  #
  dplyr::select(condition_label,
                trend_month,
                n_month_current,
                n_month_minus1,
                mean_month,
                sig_month)
```


```{r}
# NEPHU and Victorian rates for current month
results_rate <- cases_allnephu %>% 
  dplyr::filter(condition_label %in% conditions_list) %>%
  #
  f_table_dataprep_rate(conditions = conditions_list,
                        data_vic   = cases_allvic)
```


```{r}
# YTD and yearly average counts
results_ytd <- cases_allnephu %>%
  dplyr::filter(condition_label %in% conditions_list) %>%
  #
  f_table_dataprep_ytd(conditions = conditions_list)
```


```{r, results = 'asis'}
# Create, format, and display summary table in html
results_month %>%
  dplyr::left_join(results_rate, by = "condition_label") %>%
  dplyr::left_join(results_ytd, by = "condition_label") %>%
  #
  dplyr::distinct(condition_label, .keep_all = TRUE) %>%
  #
  f_table_format(data_count = results_month) %>%
  #
  kableExtra::pack_rows(conditions, 1, last_row,
                        label_row_css = "background-color: #FAF8F6; color: #191D43")

# Create and format version to save in images subfolder and send to Comms
data <- results_month %>%
  dplyr::left_join(results_rate, by = "condition_label") %>%
  dplyr::left_join(results_ytd, by = "condition_label") %>%
  #
  dplyr::distinct(condition_label, .keep_all = TRUE) %>%
  
  select(-sig_month) %>%
    mutate(
      mean_month = round(mean_month, 1),
      mean_ytd   = round(mean_ytd, 1),
      rate_nephu = round(rate_nephu, 1),
      rate_vic   = round(rate_vic, 1))

original_names <- colnames(data)
  
table <- data %>%
    gt() %>%
  
  cols_label(.list = setNames(tables_colnames, original_names)) %>%
  
    # Replace NAs with a dash
  sub_missing(
    missing_text = "-"
  ) %>%
    
    # Column alignment
    cols_align(
      align = "left",
      columns = 1
    ) %>%
    cols_align(
      align = "center",
      columns = -1
    ) %>%
    
    # Column widths
    cols_width(
      1 ~ px(250),
      2:12 ~ px(90)
    ) %>%
    
    # Shade Monthly rates section (cols 6:8)
    tab_style(
      style = cell_fill(color = "seashell"),
      locations = cells_body(columns = 6:8)
    ) %>%
    
    # Bold header
    tab_style(
      style = cell_text(weight = "bold"),
      locations = cells_column_labels(everything())
    ) %>%
    
    # Bold + red where Higher than expected
    tab_style(
      style = list(
        cell_text(weight = "bold", color = "red")
      ),
      locations = cells_body(
        rows = results_month$sig_month == "Higher than expected"
      )
    ) %>%
    
    # Italic where "**"
    tab_style(
      style = cell_text(style = "italic"),
      locations = cells_body(
        rows = results_month$sig_month == "**"
      )
    ) %>%
    
    # Multi-level column headers
    tab_spanner(
      label = "Monthly counts",
      columns = 2:5
    ) %>%
    tab_spanner(
      label = "Monthly rates",
      columns = 6:8
    ) %>%
    tab_spanner(
      label = "YTD counts",
      columns = 9:12
    ) %>%
  
  tab_style(
  style = cell_text(weight = "bold"),
  locations = cells_column_spanners(everything())
) %>% 
  
  tab_row_group(
  label = conditions,
  rows = 1:last_row
) %>% 
  
  tab_style(
  style = list(
    cell_fill(color = "#FAF8F6"),
    cell_text(color = "#191D43", weight = "bold")
  ),
  locations = cells_row_groups()
) %>% 
    
    # Font + general styling
    opt_table_font(
      font = list(
        gt::google_font("Arial"),
        default_fonts()
      )
    ) %>%
    tab_options(
      table.font.size = px(12),
      table.width = "auto"
    )

output_base <- paste0(
  "../../Reports/Images for Comms/",
  format(epimonth_current, "%Y-%m"),
  " Table ",
  conditions
)

html_file <- paste0(output_base, ".html")
gtsave(table, filename = html_file)
```

